plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

remote_theme: vszhub/not-pure-poole


title: Constanza Echiburú
description: Graduate student
url: https://csechiburu.github.io
avatar: /avatar.jpg
paginate: 5
permalink: pretty
cover_image: /cover.jpg
cover_color: rgb(64, 64, 64)
cover_bg_color: rgb(255, 255, 255)
