plugins:
  - jekyll-remote-theme

remote_theme: vszhub/not-pure-poole


title: Name
description: Welcome
url: https://cseschiburu.github.io
avatar: /avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /cover.JPG
