plugins:
  - jekyll-remote-theme

remote_theme: vszhub/not-pure-poole


title: Constanza Echiburú
description: Graduate Student
url: https://csechiburu.github.io
avatar: /avatar.jpg
paginate: 5
permalink: pretty
cover_image: /cover.jpg
